[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc_visit"
publish = false
version = "0.1.0"

[dependencies]
num-bigint = "0.2"
stc_visit_macros = {path = "./macros"}
swc_atoms = "0.2"
swc_common = "0.10.8"
swc_ecma_ast = "0.36.1"
