[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "stc_ts_types"
publish = false
version = "0.0.0"

[features]
profile = []

[lib]

[dependencies]
dashmap = "3"
fxhash = "0.2.1"
is-macro = "0.1.7"
new_debug_unreachable = "1.0.4"
num-bigint = {version = "0.4.3", features = ["serde"]}
num-traits = "0.2.12"
once_cell = "1.8.0"
parking_lot = "0.12.1"
rnode = {path = "../rnode"}
rustc-hash = "1.1.0"
scoped-tls = "1.0.0"
serde = {version = "1.0.147", features = ["derive", "rc"]}
static_assertions = "1.1.0"
stc_arc_cow = {path = "../stc_arc_cow"}
stc_ts_ast_rnode = {path = "../stc_ts_ast_rnode"}
stc_utils = {path = "../stc_utils"}
stc_visit = {path = "../stc_visit"}
swc_atoms = "0.4.39"
swc_common = {version = "0.29.37", features = ["concurrent"]}
swc_ecma_ast = "0.100.2"
swc_ecma_utils = "0.113.6"
swc_ecma_visit = "0.86.2"
swc_visit = "0.5.3"
tracing = "0.1.37"
triomphe = "0.1.8"
