[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
build = "build.rs"
edition = "2018"
name = "stc_ts_dts"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
retain_mut = "0.1.1"
rnode = {path = "../../rnode/"}
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_dts_mutations = { path = "../dts_mutations" }
stc_ts_types = {path = "../types"}
stc_ts_utils = {path = "../utils"}
swc_common = "0.10.8"
swc_ecma_ast = "0.36.2"

[dev-dependencies]
anyhow = "1.0.37"
slog = "2.7.0"
stc_testing = {path = "../../testing"}
stc_ts_file_analyzer = {path = "../file_analyzer"}
swc_common = "0.10.8"
swc_ecma_ast = "0.36.2"
swc_ecma_codegen = "0.42.2"
swc_ecma_parser = "0.44.1"
swc_ecma_transforms = "0.31.2"
swc_ecma_utils = "0.26.0"
swc_ecma_visit = "0.22.0"
testing = "0.10.2"
testing_macros = "0.1.1"
