[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "stc_ts_testing"
publish = false
version = "0.1.0"

[lib]

[dependencies]
anyhow = "1.0.66"
rnode = {path = "../rnode/"}
stc_testing = {path = "../stc_testing"}
stc_ts_ast_rnode = {path = "../stc_ts_ast_rnode"}
stc_ts_types = {path = "../stc_ts_types"}
swc_atoms = "0.4.24"
swc_common = "0.29.14"
swc_ecma_ast = "0.94.19"
swc_ecma_codegen = "0.127.31"
swc_ecma_parser = "0.122.26"
swc_ecma_transforms = "0.198.45"
swc_ecma_utils = "0.105.32"
swc_ecma_visit = "0.80.19"
