[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc_ts_testing"
publish = false
version = "0.1.0"

[dependencies]
anyhow = "1.0.37"
rnode = { path = "../../rnode/" }
stc_testing = { path = "../../testing" }
stc_ts_ast_rnode = { path = "../ast_rnode" }
stc_ts_types = { path = "../types" }
swc_atoms = "0.2.5"
swc_common = "0.10.9"
swc_ecma_ast = "0.37.3"
swc_ecma_codegen = "0.43.6"
swc_ecma_parser = "0.45.0"
swc_ecma_utils = "0.27.3"
swc_ecma_visit = "0.23.3"
