[package]
authors = ["강동윤 <kdy1@dudy.kr>"]
edition = "2018"
name = "stc_ts_file_analyzer"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.55"
bitflags = "1.2.1"
dashmap = {version = "3", features = ["raw-api"]}
derivative = "2.1.1"
fxhash = "0.2.1"
itertools = "0.10.0"
once_cell = "1.5.2"
petgraph = "0.5.1"
rayon = "1.5.0"
retain_mut = "0.1.1"
rnode = {path = "../../rnode"}
slog = "2.7.0"
smallvec = "1.5.1"
stc_ts_ast_rnode = {path = "../ast_rnode"}
stc_ts_builtin_types = {path = "../builtin_types"}
stc_ts_file_analyzer_macros = {path = "./macros"}
stc_ts_types = {path = "../types"}
stc_ts_utils = {path = "../utils"}
stc_utils = {path = "../../utils"}
swc_atoms = "0.2.5"
swc_common = {version = "0.10.8", features = ["concurrent"]}
swc_ecma_ast = "0.36.2"
swc_ecma_codegen = "0.42.2"
swc_ecma_parser = "0.44.1"
swc_ecma_utils = "0.26.0"

[dev-dependencies]
stc_testing = {path = "../../testing"}
swc_ecma_parser = "0.44.1"
swc_ecma_transforms = "0.31.2"
swc_ecma_visit = "0.22.0"
testing = "0.10.2"
