[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2021"
name = "stc_utils"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.2"
once_cell = "1"
rustc-hash = "1.1.0"
scoped-tls = "1.0.0"
swc_common = { version = "0.29.14", features = ["concurrent", "tty-emitter"] }
swc_node_base = "0.5.8"
tracing = "0.1.37"
